name: Undraft Release

on:
  workflow_call:

permissions:
  contents: write

jobs:
  undraft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          REF_NAME: ${{ github.ref_name }}
          REPOSITORY: ${{ github.repository }}
        run: gh release edit "$REF_NAME" --repo "$REPOSITORY" --draft=false
